steps:
  gctsCloneRepository:
    //host: 'http://vhcalnplci.dummy.nodomain:8000'
    host: 'http://192.168.15.36:8000'
    client: '001'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'myrepo'
